# Generated by Django 6.0.3 on 2026-04-27 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('funnel', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon', models.PositiveIntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('one time', 'One time'), ('monthly', 'Monthly')], max_length=20)),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_versions', to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Backend.price')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vpn', models.FloatField()),
                ('income_vpn', models.FloatField(default=0)),
                ('payback', models.FloatField()),
                ('contribution_percent', models.FloatField()),
                ('ebitda_total', models.FloatField()),
                ('net_margin', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Backend.priceversion')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInputs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicial_income', models.FloatField(default=0.0)),
                ('capex', models.FloatField()),
                ('opex', models.FloatField()),
                ('wacc', models.FloatField()),
                ('factor', models.FloatField(default=1.0)),
                ('sensitivity', models.FloatField(default=1.0)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='Backend.priceversion')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.PositiveIntegerField()),
                ('income', models.FloatField()),
                ('opex', models.FloatField()),
                ('ebitda', models.FloatField()),
                ('capex', models.FloatField()),
                ('fcl', models.FloatField()),
                ('discount_factor', models.FloatField()),
                ('fcl_discounted', models.FloatField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='Backend.priceversion')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.AddConstraint(
            model_name='priceversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('price', 'horizon'), name='unique_current_version_per_price_horizon'),
        ),
        migrations.AlterUniqueTogether(
            name='priceversion',
            unique_together={('price', 'horizon', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('version', 'period')},
        ),
    ]
