# Generated by Django 6.0.3 on 2026-07-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_department_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='avg_rate_pf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='zone',
            field=models.CharField(choices=[('NORTH', 'NORTE'), ('COFFEE AXIS', 'EJE CAFETERO'), ('CENTER', 'CENTRO'), ('SOUTH', 'SUR'), ('EAST', 'ORIENTE'), ('WEAST', 'OCCIDENTE'), ('BOYACA', 'Boyaca'), ('NORTE DE SANTANDER', 'Norte Santander')], default='BOYACA', max_length=50),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='Backend.department'),
        ),
    ]
