# Generated by Django 6.0.3 on 2026-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_department_avg_rate_pf_department_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='zone',
            field=models.CharField(choices=[('NORTH', 'NORTE'), ('COFFEE AXIS', 'EJE CAFETERO'), ('CENTER', 'CENTRO'), ('SOUTH', 'SUR'), ('EAST', 'ORIENTE'), ('WEAST', 'OCCIDENTE'), ('BOYACA', 'Boyaca'), ('NORTE DE SANTANDER', 'Norte Santander')], max_length=50, null=True),
        ),
    ]
