# Generated by Django 6.0.3 on 2026-07-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_department_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='avg_rate_pf',
            field=models.FloatField(null=True),
        ),
    ]
