# Generated by Django 6.0.3 on 2026-07-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_department_avg_rate_pf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='zone',
            field=models.CharField(choices=[('NORTH', 'NORTE'), ('COFFEE AXIS', 'EJE CAFETERO'), ('CENTER', 'CENTRO'), ('SOUTH', 'SUR'), ('EAST', 'ORIENTE'), ('WEST', 'OCCIDENTE'), ('BOYACA', 'Boyaca'), ('NORTE DE SANTANDER', 'Norte Santander')], max_length=50, null=True),
        ),
    ]
