# Generated by Django 6.0.3 on 2026-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_department_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='avg_rate_pf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='zone',
            field=models.CharField(choices=[('NORTH', 'NORTE'), ('COFFEE AXIS', 'EJE CAFETERO'), ('CENTER', 'CENTRO'), ('SOUTH', 'SUR'), ('EAST', 'ORIENTE'), ('WEST', 'OCCIDENTE'), ('BOYACA', 'Boyaca'), ('NORTE DE SANTANDER', 'Norte Santander'), ('NONE', 'NINGUNO')], max_length=50),
        ),
    ]
