# Generated by Django 6.0.3 on 2026-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_department_avg_rate_pf_alter_department_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='avg_rate_pf',
            field=models.FloatField(),
        ),
    ]
