# Generated by Django 6.0.3 on 2026-07-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_alter_department_avg_rate_pf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(choices=[('USD', 'Usd'), ('COP', 'Cop')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
