# Generated by Django 6.0.3 on 2026-07-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_financialvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialvariable',
            name='unit',
            field=models.CharField(choices=[('USD', 'Usd'), ('COP', 'Cop'), ('COP/USD', 'Cop Usd')], max_length=10),
        ),
    ]
