# Generated by Django 6.0.3 on 2026-07-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_financialvariable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialvariable',
            name='unit',
            field=models.CharField(choices=[('USD', 'Usd'), ('COP', 'Cop'), ('COP/USD', 'Cop Usd'), ('USD/Mbps/mes', 'Usd Mbps Mes'), ('USD/metro', 'Usd M'), ('COP/llamada', 'Cop Call'), ('USD/poste/mes', 'Usd Poste Mes'), ('USD/metro/mes', 'Usd M Mes'), ('%', 'Percent'), ('adimensional', 'Ad')], max_length=20),
        ),
    ]
