# Generated by Django 6.0.3 on 2026-07-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_financialvariable_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='node',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
