# Generated by Django 6.0.3 on 2026-07-24 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_municipality_latitude_municipality_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('pricing', 'Pricing'), ('retencion', 'Retencion'), ('ventas', 'Ventas')], max_length=30)),
                ('cargo', models.CharField(choices=[('analista', 'Analista'), ('profesional', 'Profesional'), ('lider', 'Lider'), ('gerente', 'Gerente'), ('director', 'Director')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
