# Generated by Django 6.0.3 on 2026-08-10 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_number', models.PositiveIntegerField(default=0)),
                ('identification_number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('subsegment', models.CharField(choices=[('Empresas', 'Empresas'), ('Residencial', 'Residencial'), ('ISPs', 'Isp'), ('Wholesale', 'Wholesale'), ('Gobierno', 'Gobierno'), ('Comunitario', 'Comunitario'), ('0', 'Zero'), ('No Aplica', 'N A')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.CharField(choices=[('pricing', 'Pricing'), ('retencion', 'Retencion'), ('ventas', 'Ventas'), ('preventa', 'Preventa')], max_length=30),
        ),
    ]
