# Generated by Django 6.0.3 on 2026-08-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_client_alter_userprofile_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='subsegment',
            field=models.CharField(choices=[('Negocios', 'Negocios'), ('Empresas', 'Empresas'), ('Residencial', 'Residencial'), ('ISPs', 'Isp'), ('Wholesale', 'Wholesale'), ('Gobierno', 'Gobierno'), ('Comunitario', 'Comunitario'), ('0', 'Zero'), ('No Aplica', 'N A')], max_length=30),
        ),
    ]
