# Generated by Django 6.0.3 on 2026-08-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_alter_client_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
