# Generated by Django 6.0.3 on 2026-08-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_alter_client_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='verification_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
