# Generated by Django 6.0.3 on 2026-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_alter_client_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(choices=[('analista', 'Analista'), ('profesional', 'Profesional'), ('ingeniero', 'Ingeniero'), ('lider', 'Lider'), ('gerente', 'Gerente'), ('director', 'Director')], max_length=30),
        ),
    ]
