# Generated by Django 6.0.3 on 2026-08-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='region',
            new_name='region_name',
        ),
    ]
