# Generated by Django 6.0.3 on 2026-08-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_rename_region_municipality_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Backend.region'),
        ),
    ]
