# Generated by Django 6.0.3 on 2026-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_populate_municipality_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='region_name',
        ),
    ]
