# Generated by Django 6.0.3 on 2026-08-24 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_remove_municipality_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mbps', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferencePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('BASE', 'Tarifa Base'), ('DISCOUNT', 'Tarifa con Descuento'), ('SPECIAL', 'Tarifa Especial')], default='BASE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_prices', to='Backend.capacity')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_prices', to='Backend.region')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('region', 'capacity', 'price_type'), name='unique_reference_price')],
            },
        ),
    ]
