# Generated by Django 6.0.3 on 2026-08-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_capacity_referenceprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='version',
        ),
        migrations.RemoveField(
            model_name='financialinputs',
            name='version',
        ),
        migrations.RemoveField(
            model_name='financialresults',
            name='version',
        ),
        migrations.RemoveField(
            model_name='price',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='priceversion',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='priceversion',
            name='unique_current_version_per_price_horizon',
        ),
        migrations.DeleteModel(
            name='CashFlow',
        ),
        migrations.DeleteModel(
            name='FinancialInputs',
        ),
        migrations.DeleteModel(
            name='FinancialResults',
        ),
        migrations.RemoveField(
            model_name='priceversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='priceversion',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='PriceVersion',
        ),
    ]
