# Generated by Django 6.0.3 on 2026-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0026_alter_cashflow_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('L2', 'L2'), ('L3', 'L3')], max_length=10)),
                ('product', models.CharField(choices=[('Canal Nacional', 'Canal Nacional'), ('Canal Nacional sin UK', 'Canal Nacional Sin Uk'), ('BA Corporativa', 'Ba Corporativa'), ('ID Corporativo', 'Id Corporativo'), ('Internet +', 'Internet Plus'), ('Internet Dedicado Empresarial', 'Internet Dedicado Emp'), ('Internet Dedicado sin UK', 'Internet Dedicado Sin Uk'), ('Internet Simetrico Empresarial', 'Internet Simetrico Emp'), ('Red IP', 'Red Ip')], max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('product_type', 'product')},
            },
        ),
    ]
