# Generated by Django 6.0.3 on 2026-08-25 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0027_productcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
