# Generated by Django 6.0.3 on 2026-08-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0028_alter_productcatalog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcatalog',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
