# Generated by Django 6.0.3 on 2026-08-26 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0029_rename_isactive_productcatalog_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketing_subsegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='subsegment',
            new_name='subsegment_label',
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='product',
            field=models.CharField(choices=[('Canal Nacional', 'Canal Nacional'), ('Canal Nacional Ethernet sin UK', 'Canal Nacional Sin Uk'), ('BA Corporativa', 'Ba Corporativa'), ('ID Corporativo', 'Id Corporativo'), ('Internet +', 'Internet Plus'), ('Internet Dedicado Empresarial', 'Internet Dedicado Emp'), ('Internet Dedicado sin UK', 'Internet Dedicado Sin Uk'), ('Internet Simetrico Empresarial', 'Internet Simetrico Emp'), ('Red IP', 'Red Ip')], max_length=50),
        ),
    ]
