# Generated by Django 6.0.3 on 2026-08-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_marketing_subsegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subsegment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='Backend.marketing_subsegment'),
        ),
    ]
