# Generated by Django 6.0.3 on 2026-08-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0032_migrate_client_subsegments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subsegment_label',
        ),
    ]
