# Generated by Django 6.0.3 on 2026-08-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0033_remove_client_subsegment_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marketing_subsegment',
            new_name='Subsegment',
        ),
    ]
