# Generated by Django 6.0.3 on 2026-08-27 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0034_rename_marketing_subsegment_subsegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.FloatField()),
                ('contract_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_logs', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Backend.municipality')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_logs', to='Backend.productcatalog')),
                ('subsegment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_logs', to='Backend.subsegment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
