# Generated by Django 6.0.8 on 2026-08-27 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0035_quotelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_per_mbps', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vpn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tir', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payback', models.DecimalField(decimal_places=2, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sensitivity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cashflows', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quotelog',
            name='floor_price',
        ),
        migrations.RemoveField(
            model_name='quotelog',
            name='recommended_price',
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='product',
            field=models.CharField(choices=[('Canal Nacional', 'Canal Nacional'), ('Canal Nacional Ethernet sin UK', 'Canal Nacional Sin Uk'), ('BA Corporativa', 'Ba Corporativa'), ('ID Corporativo', 'Id Corporativo'), ('Internet +', 'Internet Plus'), ('Internet Dedicado Empresarial', 'Internet Dedicado Emp'), ('Internet Dedicado sin UK', 'Internet Dedicado Sin Uk'), ('Internet Simetrico Empresarial', 'Internet Simetrico Emp'), ('Red IP', 'Red Ip'), ('IRU de Capacidad', 'Iru Capacidad')], max_length=50),
        ),
    ]
