# Generated by Django 6.0.8 on 2026-08-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0036_evaluationresults_remove_quotelog_floor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='floor_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_price_quotes', to='Backend.evaluationresults'),
        ),
        migrations.AddField(
            model_name='quotelog',
            name='suggested_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggested_price_quotes', to='Backend.evaluationresults'),
        ),
    ]
