# Generated by Django 6.0.8 on 2026-08-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0037_quotelog_floor_price_quotelog_suggested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelog',
            name='floor_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_price_quotes', to='Backend.evaluationresults'),
        ),
        migrations.AlterField(
            model_name='quotelog',
            name='suggested_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_price_quotes', to='Backend.evaluationresults'),
        ),
    ]
