# Generated by Django 6.0.8 on 2026-08-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0038_alter_quotelog_floor_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationResults',
            new_name='EvaluationResult',
        ),
    ]
