# Generated by Django 6.0.8 on 2026-08-27 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0040_referenceprice_subsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceprice',
            name='subsegment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_prices', to='Backend.subsegment'),
        ),
    ]
