# Generated by Django 6.0.8 on 2026-10-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0041_alter_referenceprice_subsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='unprofitable',
            field=models.BooleanField(default=False),
        ),
    ]
